### ISSUE TITLE
NoSuchMethodError with v2.2.0

### ISSUE THREAD

**Issue by sebakerckhof** [camunda-community-hub/zeebe-simple-monitor#346]
I try to connect the monitor to my zeebe instance (zeebe 1.2.8 and hazelcast exporter 1.0.1).
This works with simple-monitor v 2.0.0 and 2.1.0, but fails with 2.2.0, where every action I take in the monitor (e.g. deploying diagram, sending a message, ...) results in the following error:

```
zeebe-monitor_1  | Exception in thread "grpc-default-executor-0" java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3.isStringEmpty(java.lang.Object)'
zeebe-monitor_1  | 	at io.camunda.zeebe.gateway.protocol.GatewayOuterClass$ProcessRequestObject.getSerializedSize(GatewayOuterClass.java:11683)
zeebe-monitor_1  | 	at com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:877)
zeebe-monitor_1  | 	at com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:661)
zeebe-monitor_1  | 	at io.camunda.zeebe.gateway.protocol.GatewayOuterClass$DeployProcessRequest.getSerializedSize(GatewayOuterClass.java:10791)
zeebe-monitor_1  | 	at io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108)
zeebe-monitor_1  | 	at io.grpc.internal.MessageFramer.getKnownLength(MessageFramer.java:205)
zeebe-monitor_1  | 	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:137)
zeebe-monitor_1  | 	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)
zeebe-monitor_1  | 	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
zeebe-monitor_1  | 	at io.grpc.internal.DelayedStream$6.run(DelayedStream.java:283)
zeebe-monitor_1  | 	at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:182)
zeebe-monitor_1  | 	at io.grpc.internal.DelayedStream.access$100(DelayedStream.java:44)
zeebe-monitor_1  | 	at io.grpc.internal.DelayedStream$4.run(DelayedStream.java:148)
zeebe-monitor_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
zeebe-monitor_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
zeebe-monitor_1  | 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by saig0** [comment]
@sebakerckhof thank you for reporting :+1: 
I can reproduce the issue. I will check why it is failing in version `1.2.0` :thinking:

**Comment by saig0** [comment]
There is a dependency conflict with `com.google.protobuf:protobuf-java`.

```
+- io.camunda:spring-zeebe-starter:jar:1.2.8:compile
|  \- io.camunda:spring-zeebe:jar:1.2.8:compile
|     +- io.camunda:zeebe-client-java:jar:1.2.9:compile
|     |  +- com.google.protobuf:protobuf-java:jar:3.18.0:compile

+- io.zeebe.hazelcast:zeebe-hazelcast-connector:jar:1.0.1:compile
|  \- io.zeebe:zeebe-exporter-protobuf:jar:1.0.0:compile
|     \- com.google.protobuf:protobuf-java:jar:3.15.6:compile
```

I need to release a new version of `zeebe-exporter-protobuf` and `zeebe-hazelcast-connector` to fix the dependency issue.

**Comment by saig0** [comment]
Fixed by #350 :rocket:
